In [1]:
# Libraires import
import pandas as pd
import numpy as np

In [2]:
# sklearn classifiers
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [3]:
model_accuracies = {'LogReg':1, 'DT':1, 'RF':1, 'LinearSVC':1, 'KernelSVC':1, 'NB':1, 'KNN':1}

In [4]:
# Importing the data

dataset = pd.read_csv('data/Seismic-Bumps.csv', header = None)
dataset.shape

(2584, 19)

In [5]:
dataset.head()

0  1  2      3    4   5   6  7   8   9   10  11  12  13  14  15    16    17  \
0  a  a  N  15180   48 -72 -72  a   0   0   0   0   0   0   0   0     0     0   
1  a  a  N  14720   33 -70 -79  a   1   0   1   0   0   0   0   0  2000  2000   
2  a  a  N   8050   30 -81 -78  a   0   0   0   0   0   0   0   0     0     0   
3  a  a  N  28820  171 -23  40  a   1   0   1   0   0   0   0   0  3000  3000   
4  a  a  N  12640   57 -63 -52  a   0   0   0   0   0   0   0   0     0     0   

   18  
0   0  
1   0  
2   0  
3   0  
4   0

In [6]:
pd.DataFrame(pd.DataFrame(dataset.iloc[:, 7])[7].value_counts())

7
a  2342
b   212
c    30

In [7]:
pd.DataFrame(pd.DataFrame(dataset.iloc[:, 2])[2].value_counts())

2
W  1663
N   921

In [8]:
pd.DataFrame(pd.DataFrame(dataset.iloc[:, 1])[1].value_counts())

1
a  1580
b   956
c    48

In [9]:
pd.DataFrame(pd.DataFrame(dataset.iloc[:, 0])[0].value_counts())

0
a  1682
b   902

# Create X and Y

In [10]:
X = dataset.iloc[:, 0:18].values
Y = dataset.iloc[:, 18].values

In [11]:
X.shape

(2584, 18)

In [12]:
Y.shape

(2584,)

In [13]:
X[0]

array(['a', 'a', 'N', 15180, 48, -72, -72, 'a', 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0], dtype=object)

In [14]:
Y[0]

0

# Preprocess the Data

In [15]:
le_Y = LabelEncoder()

In [16]:

Y = le_Y.fit_transform(Y)

In [17]:
Y[0]

0

In [18]:
def encoder_X(index):
    le_X = LabelEncoder()
    X[:, index] = le_X.fit_transform(X[:, index])

In [19]:
to_be_encoded_indices = [0, 1, 2, 7]

In [20]:
for x in to_be_encoded_indices:
    encoder_X(x)

In [21]:
X[0]

array([0, 0, 0, 15180, 48, -72, -72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=object)

In [22]:
pd.DataFrame(pd.DataFrame(X[:, 7])[0].value_counts())

0
0  2342
1   212
2    30

In [23]:
ohe_X = OneHotEncoder(categorical_features = [7])

In [24]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(2584, 19)

In [25]:
pd.DataFrame(pd.DataFrame(X[:, 3])[0].value_counts())

0
0.0  1580
1.0   956
2.0    48

In [26]:
ohe_X = OneHotEncoder(categorical_features = [3])

In [27]:
X = ohe_X.fit_transform(X).toarray()
X = X[:, 1:]
X.shape

(2584, 20)

In [28]:
sc_X = StandardScaler()

In [29]:
X = sc_X.fit_transform(X)

In [30]:
X[0]

array([-0.76630515, -0.13757705, -0.29895828, -0.10838026, -0.73230209,
       -1.34374329, -0.32756058, -0.87207336, -1.05071094, -1.21145926,
       -0.62998398, -0.50225321, -0.51042346, -0.24273572, -0.06830542,
        0.        ,  0.        ,  0.        , -0.24332671, -0.22108685])

# Create Train and Test Data

In [31]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 4)

In [32]:
X_train.shape

(2067, 20)

In [33]:
X_test.shape

(517, 20)

In [34]:
Y_train.shape

(2067,)

In [35]:
Y_test.shape

(517,)

In [36]:
pd.DataFrame(pd.DataFrame(Y_train)[0].value_counts())

0
0  1935
1   132

In [37]:
pd.DataFrame(pd.DataFrame(Y_test)[0].value_counts())

0
0  479
1   38

# DecisionTree

In [38]:
clf_dt = DecisionTreeClassifier(criterion = 'entropy')

In [39]:
clf_dt.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [40]:
Y_pred_dt = clf_dt.predict(X_test)

In [41]:
confusion_matrix(Y_test, Y_pred_dt)

array([[450,  29],
       [ 28,  10]], dtype=int64)

# Random Forest

In [42]:
clf_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

In [43]:
clf_rf.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [44]:

Y_pred_rf = clf_rf.predict(X_test)

In [45]:
confusion_matrix(Y_test, Y_pred_rf)


array([[477,   2],
       [ 38,   0]], dtype=int64)

# Naive Bayes

In [46]:

clf_nb = GaussianNB()

In [47]:
clf_nb.fit(X_train, Y_train)

GaussianNB(priors=None)

In [48]:
Y_pred_nb = clf_nb.predict(X_test)

In [49]:
confusion_matrix(Y_test, Y_pred_nb)

array([[ 23, 456],
       [  0,  38]], dtype=int64)

# KNN

In [50]:
clf_knn = KNeighborsClassifier(n_neighbors = 5)

In [51]:
clf_knn.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [52]:
Y_pred_knn = clf_knn.predict(X_test)

In [53]:
confusion_matrix(Y_test, Y_pred_knn)

array([[476,   3],
       [ 32,   6]], dtype=int64)

# Logistic Regression

In [54]:
clf_lr = LogisticRegression()

In [55]:
clf_lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [56]:
Y_pred_lr = clf_lr.predict(X_test)

In [57]:
confusion_matrix(Y_test, Y_pred_lr)

array([[478,   1],
       [ 38,   0]], dtype=int64)

# Linear SVC

In [58]:
clf_lsvc = SVC(kernel = 'linear')

In [59]:
clf_lsvc.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [60]:
Y_pred_lsvc = clf_lsvc.predict(X_test)

In [61]:
confusion_matrix(Y_test, Y_pred_lsvc)

array([[479,   0],
       [ 38,   0]], dtype=int64)

# Kernel SVC

In [62]:
clf_ksvc = SVC(kernel = 'rbf')

In [63]:
clf_ksvc.fit(X_train, Y_train)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [64]:
Y_pred_ksvc = clf_ksvc.predict(X_test)

In [65]:
confusion_matrix(Y_test, Y_pred_ksvc)

array([[479,   0],
       [ 38,   0]], dtype=int64)

# Accuracy of Various Models


In [67]:
model_accuracies['DT'] = accuracy_score(Y_test, Y_pred_dt)
model_accuracies['KNN'] = accuracy_score(Y_test, Y_pred_knn)
model_accuracies['KernelSVC'] = accuracy_score(Y_test, Y_pred_ksvc)
model_accuracies['LinearSVC'] = accuracy_score(Y_test, Y_pred_lsvc)
model_accuracies['LogReg'] = accuracy_score(Y_test, Y_pred_lr)
model_accuracies['NB'] = accuracy_score(Y_test, Y_pred_nb)
model_accuracies['RF'] = accuracy_score(Y_test, Y_pred_rf)


In [68]:
model_accuracies

{'DT': 0.8897485493230174,
 'KNN': 0.9323017408123792,
 'KernelSVC': 0.9264990328820116,
 'LinearSVC': 0.9264990328820116,
 'LogReg': 0.9245647969052224,
 'NB': 0.11798839458413926,
 'RF': 0.9226305609284333}